causes:
  - "Stabilisateur de flux quantique grillé"
  - "Condensateur à protons surchargé"
  - "Réacteur à plasma instable"
  - "Générateur de bouclier déphasé"
  - "Cellule énergétique d’hyper-matière"
  - "Accumulateur tachyonique déchargé"
  - "Bobine supraconductrice endommagée"
  - "Synthé-câbles endommagés"
  - "Relais subspatial déconnecté"
  - "Connecteur neuro-optique oxydé"
  - "Fibre de transfert subatomique rompue"
  - "Jonction magnétique dessoudée"
  - "Nœud cybernétique défaillant"
  - "Plaques de blindage neutronisées"
  - "Microfissure dans le châssis anti-grav"
  - "Joint d’étanchéité quantique rompu"
  - "Sas anti-dépressurisation défaillant"
  - "Structure moléculaire désalignée"
  - "Circuit logique quantique corrompu"
  - "Mémoire holographique fragmentée"
  - "Module d’intelligence artificielle désynchronisé"
  - "Interface neuronale non responsive"
  - "Sous-routine d’urgence en boucle infinie"
  - "Injecteurs d’hypercarburant bouchés"
  - "Accélérateur gravimétrique bloqué"
  - "Compresseur à impulsion défaillant"
  - "Bobine hyperluminique grillée"
  - "Régulateur inertiel mal calibré"

